### ISSUE TITLE
Skip option is always set to the overwrite option

### ISSUE THREAD

**Issue by larmitage-bjss** [andrewthetechie/gha-cookiecutter#36]
**Describe the bug**
I'm trying to get cookiecutter to overwrite an existing file when generating from the template however when I switch overwrite on, the file is also skipped because skip is turned on

The bug seems to have occurred in [main.py#L91](https://github.com/andrewthetechie/gha-cookiecutter/blob/7a1866088fa15434f9846af7b7a6e81a83019923/main.py#L91) where the value passed in for 'skip' is overwritten to be the value passed in for overwrite, and the condition is duplicated - perhaps a dodgy merge?

**To Reproduce**
1. Set up a workflow using this action
2. Set the overwrite and skip options to combinations of true/false
3. See that the skip value passed in is ignored

**Expected behavior**
* Values passed in explicitly for overwrite and skip should be kept
* The documentation should clarify which one takes priority if both are set to true as they are mutually exclusive

**Screenshots**

![Screenshot 2024-06-12 at 12 53 28](https://github.com/andrewthetechie/gha-cookiecutter/assets/156074260/cbb53708-b8e6-44b3-b2cf-ddb995c877b5)

**Comment by andrewthetechie** [comment]
Nice catch @larmitage-bjss. If you setup your PR to merge back to this repo, I'll approve and merge it and get a new release cut

**Comment by andrewthetechie** [comment]
This fix will be included in 1.3.2 once this is merged https://github.com/andrewthetechie/gha-cookiecutter/pull/39
